// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package yikes

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SchemaVersion struct {
	Version int32
}

type Token struct {
	ID         int32
	Token      []byte
	SessionKey string
	Uuid       pgtype.UUID
}
