// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package yikes

import ()

type SchemaVersion struct {
	Version int32
}

type Token struct {
	ID         int32
	Token      []byte
	SessionKey string
}
