// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package yikes

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SchemaVersion struct {
	Version int32
}

type Session struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UserID    pgtype.UUID
}

type Task struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UserID    pgtype.UUID
	Summary   string
}

type Token struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Token     []byte
	UserID    pgtype.UUID
}

type User struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Email     string
}
